server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/microservicec
    username: jayi40
    password: AdminJayita@123#WBZ  # Replace <your_password> with the actual password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-77685852.okta.com/oauth2/default

      client:
        registration:
          my-internal-client:
            provider: okta
            client-id: 0oakhzm65xmIEw7Mv5d7
            client-secret: tfx-puR6RufrIUshX9fy4IN6LRLQA2lqOTafCKYgR0tnnPPschUzj-mtz0kRxlFL
            authorization-grant-type: client_credentials
            scope: internal

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#Acctuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always


#Resiliance
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000  # in milliseconds
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        eventConsumerBufferSize: 10


  retry:
    instances:
      ratingHotelRetry:
        maxAttempts: 3
        waitDuration: 500  # in milliseconds

  ratelimiter:
    instances:
      ratingHotelLimiter:
        limitForPeriod: 2
        limitRefreshPeriod: 4s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100

okta:
  oauth2:
    issuer: https://dev-77685852.okta.com/oauth2/default
    audience: api://default